name: save-size
on:
  push:
    branches:
      - main
jobs:
  save-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: run
      - name: Upload size.txt
        run: gh release upload --repo steveklabnik/size-action-test sizes --clobber size.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
